/*
* Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 */
#ifdef MS_DEBUGGER
#include "RegisterInfoPOSIX_ascend950.h"
#include "lldb/Utility/LLDBLog.h"
using namespace lldb_private;
using namespace lldb;
 
constexpr uint8_t AIC_MASK = 1U << static_cast<int>(CoreType::AIC);
constexpr uint8_t AIV_MASK = 1U << static_cast<int>(CoreType::AIV);
constexpr uint8_t MIX_MASK = AIC_MASK | AIV_MASK;
 
enum LLDB_ASCEND_RENUM {
  k_first_gpr_ascend,
  lldb_x0_ascend = k_first_gpr_ascend, lldb_x1_ascend, lldb_x2_ascend, lldb_x3_ascend,
  lldb_x4_ascend, lldb_x5_ascend, lldb_x6_ascend, lldb_x7_ascend,
  lldb_x8_ascend, lldb_x9_ascend, lldb_x10_ascend, lldb_x11_ascend,
  lldb_x12_ascend, lldb_x13_ascend, lldb_x14_ascend, lldb_x15_ascend,
  lldb_x16_ascend, lldb_x17_ascend, lldb_x18_ascend, lldb_x19_ascend,
  lldb_x20_ascend, lldb_x21_ascend, lldb_x22_ascend, lldb_x23_ascend,
  lldb_x24_ascend, lldb_x25_ascend, lldb_x26_ascend, lldb_x27_ascend,
  lldb_x28_ascend, lldb_x29_ascend, lldb_x30_ascend, lldb_x31_ascend,
  k_last_gpr_ascend = lldb_x31_ascend,
  lldb_pc_ascend, lldb_status_ascend, lldb_ctrl_su_ascend, lldb_condition_flag_ascend,
  lldb_cond_ascend, lldb_sys_cnt_ascend, lldb_safety_crc_excpt_ascend, lldb_call_depth_cnt_ascend,
  lldb_icache_prl_st_ascend, lldb_ffts_base_addr_ascend, lldb_kick_start_pc_ascend, lldb_su_warn_status_0_ascend,
  lldb_pb_slot_offset_ascend, lldb_pb_slot_id_ascend, lldb_pb_slot_occupy_bitmap_ascend, lldb_vec_event_table_ascend,
  lldb_cube_event_table_ascend, lldb_fixp_event_table_ascend, lldb_scalar_event_table_ascend,
  lldb_mte1_event_table_ascend, lldb_mte2_event_table_ascend, lldb_mte3_event_table_ascend,
  lldb_glb_get_cnt_ascend, lldb_glb_rel_cnt_ascend, lldb_set_cross_core_cnt_ascend,
  lldb_set_intra_blk_cnt_ascend,
  k_last_su_reg_ascend = lldb_set_intra_blk_cnt_ascend,
  lldb_mte_warn_ascend, lldb_l0_set_value_mte_ascend,
  lldb_padding_mte_ascend, lldb_pad_val_outtoub_ascend, lldb_pad_val_outtol1_ascend,
  lldb_loop_size_outtol1_ascend, lldb_loop1_stride_outtol1_ascend, lldb_loop2_stride_outtol1_ascend,
  lldb_loop_size_outtoub_ascend, lldb_loop1_stride_outtoub_ascend, lldb_loop2_stride_outtoub_ascend,
  lldb_loop_size_ubtoout_ascend, lldb_loop1_stride_ubtoout_ascend, lldb_loop2_stride_ubtoout_ascend,
  lldb_mte2_nz_para_ascend, lldb_mte2_src_para_ascend, lldb_pad_cnt_nddma_ascend,
  lldb_pad_val_nddma_ascend, lldb_loop0_stride_nddma_ascend, lldb_loop1_stride_nddma_ascend,
  lldb_loop2_stride_nddma_ascend, lldb_loop3_stride_nddma_ascend, lldb_loop4_stride_nddma_ascend,
  lldb_pcie_rd_ctrl_ascend, lldb_pcie_wr_ctrl_ascend, lldb_xgmma_dtc_ascend,
  lldb_xgamma_lut_inv_0_ascend, lldb_xgamma_lut_inv_1_ascend, lldb_xgamma_lut_inv_2_ascend,
  lldb_xgamma_lut_inv_3_ascend, lldb_xgamma_lut_inv_4_ascend, lldb_xgamma_lut_inv_5_ascend,
  lldb_xgamma_lut_inv_6_ascend, lldb_xgamma_lut_inv_7_ascend, lldb_xgamma_lut_inv_8_ascend,
  lldb_xgamma_lut_inv_9_ascend, lldb_xgamma_lut_inv_10_ascend, lldb_xgamma_lut_inv_11_ascend,
  lldb_xgamma_lut_inv_12_ascend, lldb_xgamma_lut_inv_13_ascend, lldb_xgamma_lut_inv_14_ascend,
  lldb_xgamma_lut_inv_15_ascend, lldb_xgamma_lut_inv_16_ascend, lldb_xgamma_lut_inv_17_ascend,
  lldb_xgamma_lut_inv_18_ascend, lldb_xgamma_lut_inv_19_ascend, lldb_xgamma_lut_inv_20_ascend,
  lldb_xgamma_lut_inv_21_ascend, lldb_xgamma_lut_inv_22_ascend, lldb_xgamma_lut_inv_23_ascend,
  lldb_xgamma_lut_inv_24_ascend, lldb_xgamma_lut_inv_25_ascend, lldb_xgamma_lut_inv_26_ascend,
  lldb_xgamma_lut_inv_27_ascend, lldb_xgamma_lut_inv_28_ascend, lldb_xgamma_lut_inv_29_ascend,
  lldb_xgamma_lut_inv_30_ascend, lldb_xgamma_lut_inv_31_ascend, lldb_xgamma_lut_inv_32_ascend,
  lldb_xgamma_lut_inv_33_ascend, lldb_xgamma_lut_imp_0_ascend, lldb_xgamma_lut_imp_1_ascend,
  lldb_xgamma_lut_imp_2_ascend, lldb_xgamma_lut_imp_3_ascend, lldb_xgamma_lut_imp_4_ascend,
  lldb_xgamma_lut_imp_5_ascend, lldb_xgamma_lut_imp_6_ascend, lldb_xgamma_lut_imp_7_ascend,
  lldb_xgamma_lut_imp_8_ascend, lldb_xgamma_lut_imp_9_ascend, lldb_xgamma_lut_imp_10_ascend,
  lldb_xgamma_lut_imp_11_ascend, lldb_xgamma_lut_imp_12_ascend, lldb_xgamma_lut_imp_13_ascend,
  lldb_xgamma_lut_imp_14_ascend, lldb_xgamma_lut_imp_15_ascend, lldb_xgamma_lut_imp_16_ascend,
  lldb_xgamma_lut_imp_17_ascend, lldb_xgamma_lut_imp_18_ascend, lldb_xgamma_lut_imp_19_ascend,
  lldb_xgamma_lut_imp_20_ascend, lldb_xgamma_lut_imp_21_ascend, lldb_xgamma_lut_imp_22_ascend,
  lldb_xgamma_lut_imp_23_ascend, lldb_xgamma_lut_imp_24_ascend, lldb_xgamma_lut_imp_25_ascend,
  lldb_xgamma_lut_imp_26_ascend, lldb_xgamma_lut_imp_27_ascend, lldb_xgamma_lut_imp_28_ascend,
  lldb_xgamma_lut_imp_29_ascend, lldb_xgamma_lut_imp_30_ascend, lldb_xgamma_lut_imp_31_ascend,
  lldb_xgamma_lut_imp_32_ascend, lldb_xgamma_lut_imp_33_ascend, lldb_xgamma_lut_imp_34_ascend,
  lldb_xgamma_lut_imp_35_ascend, lldb_xgamma_lut_imp_36_ascend, lldb_xgamma_lut_imp_37_ascend,
  lldb_xgamma_lut_imp_38_ascend, lldb_xgamma_lut_imp_39_ascend, lldb_xgamma_lut_imp_40_ascend,
  lldb_xgamma_lut_imp_41_ascend, lldb_xgamma_lut_imp_42_ascend, lldb_xgamma_lut_imp_43_ascend,
  lldb_xgamma_lut_imp_44_ascend, lldb_xgamma_lut_imp_45_ascend, lldb_xgamma_lut_imp_46_ascend,
  lldb_xgamma_lut_imp_47_ascend, lldb_xgamma_lut_imp_48_ascend, lldb_xgamma_lut_imp_49_ascend,
  lldb_xgamma_lut_imp_50_ascend, lldb_xgamma_lut_imp_51_ascend, lldb_xgamma_lut_imp_52_ascend,
  lldb_xgamma_lut_imp_53_ascend, lldb_xgamma_lut_imp_54_ascend, lldb_xgamma_lut_imp_55_ascend,
  lldb_xgamma_lut_imp_56_ascend, lldb_xgamma_lut_imp_57_ascend, lldb_xgamma_lut_imp_58_ascend,
  lldb_xgamma_lut_imp_59_ascend, lldb_xgamma_lut_imp_60_ascend, lldb_xgamma_lut_imp_61_ascend,
  lldb_xgamma_lut_imp_62_ascend, lldb_xgamma_lut_imp_63_ascend, lldb_xgamma_lut_imp_64_ascend,
  lldb_xgamma_lut_imp_65_ascend,
  k_last_mte_reg_ascend = lldb_xgamma_lut_imp_65_ascend,
  lldb_vreg0_ascend, lldb_vreg1_ascend, lldb_vreg2_ascend,
  lldb_vreg3_ascend, lldb_vreg4_ascend, lldb_vreg5_ascend, lldb_vreg6_ascend,
  lldb_vreg7_ascend, lldb_vreg8_ascend, lldb_vreg9_ascend, lldb_vreg10_ascend,
  lldb_vreg11_ascend, lldb_vreg12_ascend, lldb_vreg13_ascend, lldb_vreg14_ascend,
  lldb_vreg15_ascend, lldb_vreg16_ascend, lldb_vreg17_ascend, lldb_vreg18_ascend,
  lldb_vreg19_ascend, lldb_vreg20_ascend, lldb_vreg21_ascend, lldb_vreg22_ascend,
  lldb_vreg23_ascend, lldb_vreg24_ascend, lldb_vreg25_ascend, lldb_vreg26_ascend,
  lldb_vreg27_ascend, lldb_vreg28_ascend, lldb_vreg29_ascend, lldb_vreg30_ascend,
  lldb_vreg31_ascend, lldb_preg0_ascend, lldb_preg1_ascend, lldb_preg2_ascend,
  lldb_preg3_ascend, lldb_preg4_ascend, lldb_preg5_ascend, lldb_preg6_ascend,
  lldb_preg7_ascend, lldb_uld_0_ascend, lldb_uld_1_ascend, lldb_uld_2_ascend,
  lldb_uld_3_ascend, lldb_ust_data_0_ascend, lldb_ust_data_1_ascend, lldb_ust_data_2_ascend,
  lldb_ust_data_3_ascend, lldb_ust_flag_0_ascend, lldb_ust_flag_1_ascend, lldb_ust_flag_2_ascend,
  lldb_ust_flag_3_ascend, lldb_sreg_0_ascend, lldb_sreg_1_ascend, lldb_sreg_2_ascend,
  lldb_sreg_3_ascend, lldb_sreg_4_ascend, lldb_sreg_5_ascend, lldb_sreg_6_ascend,
  lldb_sreg_7_ascend, lldb_sreg_8_ascend, lldb_sreg_9_ascend, lldb_sreg_10_ascend,
  lldb_sreg_11_ascend, lldb_sreg_12_ascend, lldb_sreg_13_ascend, lldb_sreg_14_ascend,
  lldb_sreg_15_ascend, lldb_sreg_16_ascend, lldb_sreg_17_ascend, lldb_sreg_18_ascend,
  lldb_sreg_19_ascend, lldb_sreg_20_ascend, lldb_sreg_21_ascend, lldb_sreg_22_ascend,
  lldb_sreg_23_ascend, lldb_sreg_24_ascend, lldb_sreg_25_ascend, lldb_sreg_26_ascend,
  lldb_sreg_27_ascend, lldb_sreg_28_ascend, lldb_sreg_29_ascend, lldb_sreg_30_ascend,
  lldb_sreg_31_ascend, lldb_sreg_32_ascend, lldb_sreg_33_ascend, lldb_sreg_34_ascend,
  lldb_sreg_35_ascend, lldb_sreg_36_ascend, lldb_sreg_37_ascend, lldb_sreg_38_ascend,
  lldb_sreg_39_ascend, lldb_sreg_40_ascend, lldb_sreg_41_ascend, lldb_sreg_42_ascend,
  lldb_sreg_43_ascend, lldb_sreg_44_ascend, lldb_sreg_45_ascend, lldb_sreg_46_ascend,
  lldb_sreg_47_ascend, lldb_sreg_48_ascend, lldb_sreg_49_ascend, lldb_sreg_50_ascend,
  lldb_sreg_51_ascend, lldb_sreg_52_ascend, lldb_sreg_53_ascend, lldb_sreg_54_ascend,
  lldb_sreg_55_ascend, lldb_sreg_56_ascend, lldb_sreg_57_ascend, lldb_sreg_58_ascend,
  lldb_sreg_59_ascend, lldb_sreg_60_ascend, lldb_sreg_61_ascend, lldb_sreg_62_ascend,
  lldb_sreg_63_ascend, lldb_va_0_ascend, lldb_va_1_ascend, lldb_va_2_ascend,
  lldb_va_3_ascend, lldb_va_4_ascend, lldb_va_5_ascend, lldb_va_6_ascend,
  lldb_va_7_ascend, lldb_areg_0_ascend, lldb_areg_1_ascend, lldb_areg_2_ascend,
  lldb_areg_3_ascend, lldb_areg_4_ascend, lldb_areg_5_ascend, lldb_areg_6_ascend,
  lldb_areg_7_ascend, lldb_mask_ascend, lldb_ar_ascend, lldb_vms4_sr_ascend,
  lldb_sqzn_ascend, lldb_vpc_ascend, lldb_vl_ascend, lldb_agu_am_const_0_ascend,
  lldb_agu_am_const_1_ascend, lldb_agu_am_const_2_ascend, lldb_agu_am_const_3_ascend, lldb_agu_am_const_4_ascend,
  lldb_agu_am_const_5_ascend, lldb_agu_am_const_6_ascend, lldb_agu_am_const_7_ascend, lldb_agu_am_const_8_ascend,
  lldb_agu_am_const_9_ascend, lldb_agu_am_const_10_ascend, lldb_agu_am_const_11_ascend, lldb_agu_am_const_12_ascend,
  lldb_agu_am_const_13_ascend, lldb_agu_am_const_14_ascend, lldb_agu_am_const_15_ascend, lldb_agu_am_const_16_ascend,
  lldb_agu_am_const_17_ascend, lldb_agu_am_const_18_ascend, lldb_agu_am_const_19_ascend, lldb_agu_am_const_20_ascend,
  lldb_agu_am_const_21_ascend, lldb_agu_am_const_22_ascend, lldb_agu_am_const_23_ascend, lldb_agu_am_const_24_ascend,
  lldb_agu_am_const_25_ascend, lldb_agu_am_const_26_ascend, lldb_agu_am_const_27_ascend, lldb_agu_am_const_28_ascend,
  lldb_agu_am_const_29_ascend, lldb_agu_am_const_30_ascend, lldb_agu_am_const_31_ascend, lldb_agu_am_const_32_ascend,
  lldb_agu_am_const_33_ascend, lldb_agu_am_const_34_ascend, lldb_agu_am_const_35_ascend, lldb_agu_am_const_36_ascend,
  lldb_agu_am_const_37_ascend, lldb_agu_am_const_38_ascend, lldb_agu_am_const_39_ascend, lldb_agu_am_const_40_ascend,
  lldb_agu_am_const_41_ascend, lldb_agu_am_const_42_ascend, lldb_agu_am_const_43_ascend, lldb_agu_am_const_44_ascend,
  lldb_agu_am_const_45_ascend, lldb_agu_am_const_46_ascend, lldb_agu_am_const_47_ascend, lldb_agu_am_const_48_ascend,
  lldb_agu_am_const_49_ascend, lldb_agu_am_const_50_ascend, lldb_agu_am_const_51_ascend, lldb_agu_am_const_52_ascend,
  lldb_agu_am_const_53_ascend, lldb_agu_am_const_54_ascend, lldb_agu_am_const_55_ascend, lldb_agu_am_const_56_ascend,
  lldb_agu_am_const_57_ascend, lldb_agu_am_const_58_ascend, lldb_agu_am_const_59_ascend, lldb_agu_am_const_60_ascend,
  lldb_agu_am_const_61_ascend, lldb_agu_am_const_62_ascend, lldb_agu_am_const_63_ascend, lldb_ust_ele_ofs_0_ascend,
  lldb_ust_ele_ofs_1_ascend, lldb_ust_ele_ofs_2_ascend, lldb_ust_ele_ofs_3_ascend, lldb_core_id_ascend,
  lldb_vec_core_id_ascend, lldb_vthreaddim_x_ascend, lldb_vthreaddim_y_ascend, lldb_vthreaddim_z_ascend,
  lldb_simt_pc_ascend, lldb_mrf_ascend, lldb_p_register_ascend, lldb_execmask_ascend,
  k_last_vecrb_reg_ascend = lldb_execmask_ascend,
  lldb_fmatrix_ascend, lldb_padding_l1_ascend, lldb_l0_set_value_l1_ascend, lldb_l1_3d_size_ascend,
  lldb_l3d_rpt_ascend, lldb_fmatrix_dual_0_ascend, lldb_fmatrix_dual_1_ascend, lldb_fmatrix_b_ascend,
  lldb_l3d_rpt_b_ascend, lldb_padding_b_ascend, lldb_relu_alpha_ascend, lldb_quant_post_ascend,
  lldb_fpc_ascend, lldb_quant_pre_ascend, lldb_elt_src_para_ascend, lldb_loop3_para_ascend,
  lldb_fix_clip_relu_ascend, lldb_loop4_para_ascend, lldb_channel_para_ascend, lldb_elt_antiq_para_ascend,
  lldb_l1_warn_ascend,
  k_last_l1_reg_ascend = lldb_l1_warn_ascend,
  k_num_registers_ascend
};
 
enum {
  k_num_gpr_registers = k_last_gpr_ascend - k_first_gpr_ascend + 1,
  k_num_su_registers = k_last_su_reg_ascend + 1,
  k_num_mte_registers = k_last_mte_reg_ascend - k_last_su_reg_ascend,
  k_num_vecrb_registers = k_last_vecrb_reg_ascend - k_last_mte_reg_ascend,
  k_num_l1_registers = k_last_l1_reg_ascend - k_last_vecrb_reg_ascend,
  k_num_register_sets_default = 1,
  k_num_register_sets = 4
};
 
static const uint32_t g_su_regnums_ascend950[] = {
  lldb_x0_ascend, lldb_x1_ascend, lldb_x2_ascend, lldb_x3_ascend,
  lldb_x4_ascend, lldb_x5_ascend, lldb_x6_ascend, lldb_x7_ascend,
  lldb_x8_ascend, lldb_x9_ascend, lldb_x10_ascend, lldb_x11_ascend,
  lldb_x12_ascend, lldb_x13_ascend, lldb_x14_ascend, lldb_x15_ascend,
  lldb_x16_ascend, lldb_x17_ascend, lldb_x18_ascend, lldb_x19_ascend,
  lldb_x20_ascend, lldb_x21_ascend, lldb_x22_ascend, lldb_x23_ascend,
  lldb_x24_ascend, lldb_x25_ascend, lldb_x26_ascend, lldb_x27_ascend,
  lldb_x28_ascend, lldb_x29_ascend, lldb_x30_ascend, lldb_x31_ascend,
  lldb_pc_ascend, lldb_status_ascend, lldb_ctrl_su_ascend, lldb_condition_flag_ascend,
  lldb_cond_ascend, lldb_sys_cnt_ascend, lldb_safety_crc_excpt_ascend, lldb_call_depth_cnt_ascend,
  lldb_icache_prl_st_ascend, lldb_ffts_base_addr_ascend, lldb_kick_start_pc_ascend, lldb_su_warn_status_0_ascend,
  lldb_pb_slot_offset_ascend, lldb_pb_slot_id_ascend, lldb_pb_slot_occupy_bitmap_ascend, lldb_vec_event_table_ascend,
  lldb_cube_event_table_ascend, lldb_fixp_event_table_ascend, lldb_scalar_event_table_ascend,
  lldb_mte1_event_table_ascend, lldb_mte2_event_table_ascend, lldb_mte3_event_table_ascend,
  lldb_glb_get_cnt_ascend, lldb_glb_rel_cnt_ascend, lldb_set_cross_core_cnt_ascend,
  lldb_set_intra_blk_cnt_ascend, LLDB_INVALID_REGNUM
};
 
static_assert(sizeof(g_su_regnums_ascend950) / sizeof(uint32_t) - 1 == k_num_su_registers,
              "Invalid size of g_su_regnums_ascend950");
 
static const uint32_t g_mte_regnums_ascend950[] = {
  lldb_mte_warn_ascend, lldb_l0_set_value_mte_ascend,
  lldb_padding_mte_ascend, lldb_pad_val_outtoub_ascend, lldb_pad_val_outtol1_ascend,
  lldb_loop_size_outtol1_ascend, lldb_loop1_stride_outtol1_ascend, lldb_loop2_stride_outtol1_ascend,
  lldb_loop_size_outtoub_ascend, lldb_loop1_stride_outtoub_ascend, lldb_loop2_stride_outtoub_ascend,
  lldb_loop_size_ubtoout_ascend, lldb_loop1_stride_ubtoout_ascend, lldb_loop2_stride_ubtoout_ascend,
  lldb_mte2_nz_para_ascend, lldb_mte2_src_para_ascend, lldb_pad_cnt_nddma_ascend,
  lldb_pad_val_nddma_ascend, lldb_loop0_stride_nddma_ascend, lldb_loop1_stride_nddma_ascend,
  lldb_loop2_stride_nddma_ascend, lldb_loop3_stride_nddma_ascend, lldb_loop4_stride_nddma_ascend,
  lldb_pcie_rd_ctrl_ascend, lldb_pcie_wr_ctrl_ascend, lldb_xgmma_dtc_ascend,
  lldb_xgamma_lut_inv_0_ascend, lldb_xgamma_lut_inv_1_ascend, lldb_xgamma_lut_inv_2_ascend,
  lldb_xgamma_lut_inv_3_ascend, lldb_xgamma_lut_inv_4_ascend, lldb_xgamma_lut_inv_5_ascend,
  lldb_xgamma_lut_inv_6_ascend, lldb_xgamma_lut_inv_7_ascend, lldb_xgamma_lut_inv_8_ascend,
  lldb_xgamma_lut_inv_9_ascend, lldb_xgamma_lut_inv_10_ascend, lldb_xgamma_lut_inv_11_ascend,
  lldb_xgamma_lut_inv_12_ascend, lldb_xgamma_lut_inv_13_ascend, lldb_xgamma_lut_inv_14_ascend,
  lldb_xgamma_lut_inv_15_ascend, lldb_xgamma_lut_inv_16_ascend, lldb_xgamma_lut_inv_17_ascend,
  lldb_xgamma_lut_inv_18_ascend, lldb_xgamma_lut_inv_19_ascend, lldb_xgamma_lut_inv_20_ascend,
  lldb_xgamma_lut_inv_21_ascend, lldb_xgamma_lut_inv_22_ascend, lldb_xgamma_lut_inv_23_ascend,
  lldb_xgamma_lut_inv_24_ascend, lldb_xgamma_lut_inv_25_ascend, lldb_xgamma_lut_inv_26_ascend,
  lldb_xgamma_lut_inv_27_ascend, lldb_xgamma_lut_inv_28_ascend, lldb_xgamma_lut_inv_29_ascend,
  lldb_xgamma_lut_inv_30_ascend, lldb_xgamma_lut_inv_31_ascend, lldb_xgamma_lut_inv_32_ascend,
  lldb_xgamma_lut_inv_33_ascend, lldb_xgamma_lut_imp_0_ascend, lldb_xgamma_lut_imp_1_ascend,
  lldb_xgamma_lut_imp_2_ascend, lldb_xgamma_lut_imp_3_ascend, lldb_xgamma_lut_imp_4_ascend,
  lldb_xgamma_lut_imp_5_ascend, lldb_xgamma_lut_imp_6_ascend, lldb_xgamma_lut_imp_7_ascend,
  lldb_xgamma_lut_imp_8_ascend, lldb_xgamma_lut_imp_9_ascend, lldb_xgamma_lut_imp_10_ascend,
  lldb_xgamma_lut_imp_11_ascend, lldb_xgamma_lut_imp_12_ascend, lldb_xgamma_lut_imp_13_ascend,
  lldb_xgamma_lut_imp_14_ascend, lldb_xgamma_lut_imp_15_ascend, lldb_xgamma_lut_imp_16_ascend,
  lldb_xgamma_lut_imp_17_ascend, lldb_xgamma_lut_imp_18_ascend, lldb_xgamma_lut_imp_19_ascend,
  lldb_xgamma_lut_imp_20_ascend, lldb_xgamma_lut_imp_21_ascend, lldb_xgamma_lut_imp_22_ascend,
  lldb_xgamma_lut_imp_23_ascend, lldb_xgamma_lut_imp_24_ascend, lldb_xgamma_lut_imp_25_ascend,
  lldb_xgamma_lut_imp_26_ascend, lldb_xgamma_lut_imp_27_ascend, lldb_xgamma_lut_imp_28_ascend,
  lldb_xgamma_lut_imp_29_ascend, lldb_xgamma_lut_imp_30_ascend, lldb_xgamma_lut_imp_31_ascend,
  lldb_xgamma_lut_imp_32_ascend, lldb_xgamma_lut_imp_33_ascend, lldb_xgamma_lut_imp_34_ascend,
  lldb_xgamma_lut_imp_35_ascend, lldb_xgamma_lut_imp_36_ascend, lldb_xgamma_lut_imp_37_ascend,
  lldb_xgamma_lut_imp_38_ascend, lldb_xgamma_lut_imp_39_ascend, lldb_xgamma_lut_imp_40_ascend,
  lldb_xgamma_lut_imp_41_ascend, lldb_xgamma_lut_imp_42_ascend, lldb_xgamma_lut_imp_43_ascend,
  lldb_xgamma_lut_imp_44_ascend, lldb_xgamma_lut_imp_45_ascend, lldb_xgamma_lut_imp_46_ascend,
  lldb_xgamma_lut_imp_47_ascend, lldb_xgamma_lut_imp_48_ascend, lldb_xgamma_lut_imp_49_ascend,
  lldb_xgamma_lut_imp_50_ascend, lldb_xgamma_lut_imp_51_ascend, lldb_xgamma_lut_imp_52_ascend,
  lldb_xgamma_lut_imp_53_ascend, lldb_xgamma_lut_imp_54_ascend, lldb_xgamma_lut_imp_55_ascend,
  lldb_xgamma_lut_imp_56_ascend, lldb_xgamma_lut_imp_57_ascend, lldb_xgamma_lut_imp_58_ascend,
  lldb_xgamma_lut_imp_59_ascend, lldb_xgamma_lut_imp_60_ascend, lldb_xgamma_lut_imp_61_ascend,
  lldb_xgamma_lut_imp_62_ascend, lldb_xgamma_lut_imp_63_ascend, lldb_xgamma_lut_imp_64_ascend,
  lldb_xgamma_lut_imp_65_ascend, LLDB_INVALID_REGNUM
};
 
static_assert(sizeof(g_mte_regnums_ascend950) / sizeof(uint32_t) - 1 == k_num_mte_registers,
              "Invalid size of g_mte_regnums_ascend950");
 
static const uint32_t g_vecrb_regnums_ascend950[] = {
  lldb_vreg0_ascend, lldb_vreg1_ascend, lldb_vreg2_ascend,
  lldb_vreg3_ascend, lldb_vreg4_ascend, lldb_vreg5_ascend, lldb_vreg6_ascend,
  lldb_vreg7_ascend, lldb_vreg8_ascend, lldb_vreg9_ascend, lldb_vreg10_ascend,
  lldb_vreg11_ascend, lldb_vreg12_ascend, lldb_vreg13_ascend, lldb_vreg14_ascend,
  lldb_vreg15_ascend, lldb_vreg16_ascend, lldb_vreg17_ascend, lldb_vreg18_ascend,
  lldb_vreg19_ascend, lldb_vreg20_ascend, lldb_vreg21_ascend, lldb_vreg22_ascend,
  lldb_vreg23_ascend, lldb_vreg24_ascend, lldb_vreg25_ascend, lldb_vreg26_ascend,
  lldb_vreg27_ascend, lldb_vreg28_ascend, lldb_vreg29_ascend, lldb_vreg30_ascend,
  lldb_vreg31_ascend, lldb_preg0_ascend, lldb_preg1_ascend, lldb_preg2_ascend,
  lldb_preg3_ascend, lldb_preg4_ascend, lldb_preg5_ascend, lldb_preg6_ascend,
  lldb_preg7_ascend, lldb_uld_0_ascend, lldb_uld_1_ascend, lldb_uld_2_ascend,
  lldb_uld_3_ascend, lldb_ust_data_0_ascend, lldb_ust_data_1_ascend, lldb_ust_data_2_ascend,
  lldb_ust_data_3_ascend, lldb_ust_flag_0_ascend, lldb_ust_flag_1_ascend, lldb_ust_flag_2_ascend,
  lldb_ust_flag_3_ascend, lldb_sreg_0_ascend, lldb_sreg_1_ascend, lldb_sreg_2_ascend,
  lldb_sreg_3_ascend, lldb_sreg_4_ascend, lldb_sreg_5_ascend, lldb_sreg_6_ascend,
  lldb_sreg_7_ascend, lldb_sreg_8_ascend, lldb_sreg_9_ascend, lldb_sreg_10_ascend,
  lldb_sreg_11_ascend, lldb_sreg_12_ascend, lldb_sreg_13_ascend, lldb_sreg_14_ascend,
  lldb_sreg_15_ascend, lldb_sreg_16_ascend, lldb_sreg_17_ascend, lldb_sreg_18_ascend,
  lldb_sreg_19_ascend, lldb_sreg_20_ascend, lldb_sreg_21_ascend, lldb_sreg_22_ascend,
  lldb_sreg_23_ascend, lldb_sreg_24_ascend, lldb_sreg_25_ascend, lldb_sreg_26_ascend,
  lldb_sreg_27_ascend, lldb_sreg_28_ascend, lldb_sreg_29_ascend, lldb_sreg_30_ascend,
  lldb_sreg_31_ascend, lldb_sreg_32_ascend, lldb_sreg_33_ascend, lldb_sreg_34_ascend,
  lldb_sreg_35_ascend, lldb_sreg_36_ascend, lldb_sreg_37_ascend, lldb_sreg_38_ascend,
  lldb_sreg_39_ascend, lldb_sreg_40_ascend, lldb_sreg_41_ascend, lldb_sreg_42_ascend,
  lldb_sreg_43_ascend, lldb_sreg_44_ascend, lldb_sreg_45_ascend, lldb_sreg_46_ascend,
  lldb_sreg_47_ascend, lldb_sreg_48_ascend, lldb_sreg_49_ascend, lldb_sreg_50_ascend,
  lldb_sreg_51_ascend, lldb_sreg_52_ascend, lldb_sreg_53_ascend, lldb_sreg_54_ascend,
  lldb_sreg_55_ascend, lldb_sreg_56_ascend, lldb_sreg_57_ascend, lldb_sreg_58_ascend,
  lldb_sreg_59_ascend, lldb_sreg_60_ascend, lldb_sreg_61_ascend, lldb_sreg_62_ascend,
  lldb_sreg_63_ascend, lldb_va_0_ascend, lldb_va_1_ascend, lldb_va_2_ascend,
  lldb_va_3_ascend, lldb_va_4_ascend, lldb_va_5_ascend, lldb_va_6_ascend,
  lldb_va_7_ascend, lldb_areg_0_ascend, lldb_areg_1_ascend, lldb_areg_2_ascend,
  lldb_areg_3_ascend, lldb_areg_4_ascend, lldb_areg_5_ascend, lldb_areg_6_ascend,
  lldb_areg_7_ascend, lldb_mask_ascend, lldb_ar_ascend, lldb_vms4_sr_ascend,
  lldb_sqzn_ascend, lldb_vpc_ascend, lldb_vl_ascend, lldb_agu_am_const_0_ascend,
  lldb_agu_am_const_1_ascend, lldb_agu_am_const_2_ascend, lldb_agu_am_const_3_ascend, lldb_agu_am_const_4_ascend,
  lldb_agu_am_const_5_ascend, lldb_agu_am_const_6_ascend, lldb_agu_am_const_7_ascend, lldb_agu_am_const_8_ascend,
  lldb_agu_am_const_9_ascend, lldb_agu_am_const_10_ascend, lldb_agu_am_const_11_ascend, lldb_agu_am_const_12_ascend,
  lldb_agu_am_const_13_ascend, lldb_agu_am_const_14_ascend, lldb_agu_am_const_15_ascend, lldb_agu_am_const_16_ascend,
  lldb_agu_am_const_17_ascend, lldb_agu_am_const_18_ascend, lldb_agu_am_const_19_ascend, lldb_agu_am_const_20_ascend,
  lldb_agu_am_const_21_ascend, lldb_agu_am_const_22_ascend, lldb_agu_am_const_23_ascend, lldb_agu_am_const_24_ascend,
  lldb_agu_am_const_25_ascend, lldb_agu_am_const_26_ascend, lldb_agu_am_const_27_ascend, lldb_agu_am_const_28_ascend,
  lldb_agu_am_const_29_ascend, lldb_agu_am_const_30_ascend, lldb_agu_am_const_31_ascend, lldb_agu_am_const_32_ascend,
  lldb_agu_am_const_33_ascend, lldb_agu_am_const_34_ascend, lldb_agu_am_const_35_ascend, lldb_agu_am_const_36_ascend,
  lldb_agu_am_const_37_ascend, lldb_agu_am_const_38_ascend, lldb_agu_am_const_39_ascend, lldb_agu_am_const_40_ascend,
  lldb_agu_am_const_41_ascend, lldb_agu_am_const_42_ascend, lldb_agu_am_const_43_ascend, lldb_agu_am_const_44_ascend,
  lldb_agu_am_const_45_ascend, lldb_agu_am_const_46_ascend, lldb_agu_am_const_47_ascend, lldb_agu_am_const_48_ascend,
  lldb_agu_am_const_49_ascend, lldb_agu_am_const_50_ascend, lldb_agu_am_const_51_ascend, lldb_agu_am_const_52_ascend,
  lldb_agu_am_const_53_ascend, lldb_agu_am_const_54_ascend, lldb_agu_am_const_55_ascend, lldb_agu_am_const_56_ascend,
  lldb_agu_am_const_57_ascend, lldb_agu_am_const_58_ascend, lldb_agu_am_const_59_ascend, lldb_agu_am_const_60_ascend,
  lldb_agu_am_const_61_ascend, lldb_agu_am_const_62_ascend, lldb_agu_am_const_63_ascend, lldb_ust_ele_ofs_0_ascend,
  lldb_ust_ele_ofs_1_ascend, lldb_ust_ele_ofs_2_ascend, lldb_ust_ele_ofs_3_ascend, lldb_core_id_ascend,
  lldb_vec_core_id_ascend, lldb_vthreaddim_x_ascend, lldb_vthreaddim_y_ascend, lldb_vthreaddim_z_ascend,
  lldb_simt_pc_ascend, lldb_mrf_ascend, lldb_p_register_ascend, lldb_execmask_ascend, LLDB_INVALID_REGNUM
};
 
static_assert(sizeof(g_vecrb_regnums_ascend950) / sizeof(uint32_t) - 1 == k_num_vecrb_registers,
              "Invalid size of g_vecrb_regnums_ascend950");
 
static const uint32_t g_l1_regnums_ascend950[] = {
  lldb_fmatrix_ascend, lldb_padding_l1_ascend, lldb_l0_set_value_l1_ascend, lldb_l1_3d_size_ascend,
  lldb_l3d_rpt_ascend, lldb_fmatrix_dual_0_ascend, lldb_fmatrix_dual_1_ascend, lldb_fmatrix_b_ascend,
  lldb_l3d_rpt_b_ascend, lldb_padding_b_ascend, lldb_relu_alpha_ascend, lldb_quant_post_ascend,
  lldb_fpc_ascend, lldb_quant_pre_ascend, lldb_elt_src_para_ascend, lldb_loop3_para_ascend,
  lldb_fix_clip_relu_ascend, lldb_loop4_para_ascend, lldb_channel_para_ascend, lldb_elt_antiq_para_ascend,
  lldb_l1_warn_ascend, LLDB_INVALID_REGNUM
};
 
static const RegisterSet g_reg_sets_ascend950[k_num_register_sets_default] = {
  {"Registers", "register", k_num_su_registers,
   g_su_regnums_ascend950}};
 
static constexpr uint64_t SU_ID = 1UL;
static constexpr uint64_t MTE_ID = 2UL;
static constexpr uint64_t VEC_ID = 3UL;
static constexpr uint64_t CUBE_ID = 4UL;
static constexpr uint64_t BIU_ID = 5UL;
static constexpr uint64_t L1_ID = 6UL;
static constexpr uint64_t ID_OFFSET = 52UL;
 
// The array should be POD type.
static const DeviceRegisterInfo REGISTER_950_INFO[] = {
  {ASCEND_GPR(GPR0, x0, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 0, MIX_MASK},
  {ASCEND_GPR(GPR1, x1, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 1, MIX_MASK},
  {ASCEND_GPR(GPR2, x2, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 2, MIX_MASK},
  {ASCEND_GPR(GPR3, x3, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 3, MIX_MASK},
  {ASCEND_GPR(GPR4, x4, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 4, MIX_MASK},
  {ASCEND_GPR(GPR5, x5, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 5, MIX_MASK},
  {ASCEND_GPR(GPR6, x6, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 6, MIX_MASK},
  {ASCEND_GPR(GPR7, x7, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 7, MIX_MASK},
  {ASCEND_GPR(GPR8, x8, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 8, MIX_MASK},
  {ASCEND_GPR(GPR9, x9, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 9, MIX_MASK},
  {ASCEND_GPR(GPR10, x10, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 10, MIX_MASK},
  {ASCEND_GPR(GPR11, x11, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 11, MIX_MASK},
  {ASCEND_GPR(GPR12, x12, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 12, MIX_MASK},
  {ASCEND_GPR(GPR13, x13, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 13, MIX_MASK},
  {ASCEND_GPR(GPR14, x14, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 14, MIX_MASK},
  {ASCEND_GPR(GPR15, x15, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 15, MIX_MASK},
  {ASCEND_GPR(GPR16, x16, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 16, MIX_MASK},
  {ASCEND_GPR(GPR17, x17, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 17, MIX_MASK},
  {ASCEND_GPR(GPR18, x18, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 18, MIX_MASK},
  {ASCEND_GPR(GPR19, x19, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 19, MIX_MASK},
  {ASCEND_GPR(GPR20, x20, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 20, MIX_MASK},
  {ASCEND_GPR(GPR21, x21, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 21, MIX_MASK},
  {ASCEND_GPR(GPR22, x22, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 22, MIX_MASK},
  {ASCEND_GPR(GPR23, x23, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 23, MIX_MASK},
  {ASCEND_GPR(GPR24, x24, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 24, MIX_MASK},
  {ASCEND_GPR(GPR25, x25, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 25, MIX_MASK},
  {ASCEND_GPR(GPR26, x26, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 26, MIX_MASK},
  {ASCEND_GPR(GPR27, x27, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 27, MIX_MASK},
  {ASCEND_GPR(GPR28, x28, LLDB_INVALID_REGNUM), SU_ID << ID_OFFSET | 28, MIX_MASK},
  {ASCEND_GPR_ALT(GPR29, x29, fp, LLDB_REGNUM_GENERIC_FP), SU_ID << ID_OFFSET | 29, MIX_MASK},
  {ASCEND_GPR_ALT(GPR30, x30, sp, LLDB_REGNUM_GENERIC_SP), SU_ID << ID_OFFSET | 30, MIX_MASK},
  {ASCEND_GPR_ALT(GPR31, x31, lr, LLDB_REGNUM_GENERIC_RA), SU_ID << ID_OFFSET | 31, MIX_MASK},
  {ASCEND_GPR(PC, pc, LLDB_REGNUM_GENERIC_PC), SU_ID << ID_OFFSET | 64, MIX_MASK},
  {ASCEND_REG(STATUS, lldb_status_ascend), SU_ID << ID_OFFSET | 65, MIX_MASK},
  {ASCEND_REG(CTRL_SU, lldb_ctrl_su_ascend), SU_ID << ID_OFFSET | 66, MIX_MASK},
  {ASCEND_REG(CONDITION_FLAG, lldb_condition_flag_ascend), SU_ID << ID_OFFSET | 67, MIX_MASK},
  {ASCEND_REG(COND, lldb_cond_ascend), SU_ID << ID_OFFSET | 68, MIX_MASK},
  {ASCEND_REG(SYS_CNT, lldb_sys_cnt_ascend), SU_ID << ID_OFFSET | 69, MIX_MASK},
  {ASCEND_REG(SAFETY_CRC_EXCPT, lldb_safety_crc_excpt_ascend), SU_ID << ID_OFFSET | 71, MIX_MASK},
  {ASCEND_REG(CALL_DEPTH_CNT, lldb_call_depth_cnt_ascend), SU_ID << ID_OFFSET | 72, MIX_MASK},
  {ASCEND_REG(ICACHE_PRL_ST, lldb_icache_prl_st_ascend), SU_ID << ID_OFFSET | 73, MIX_MASK},
  {ASCEND_REG(FFTS_BASE_ADDR, lldb_ffts_base_addr_ascend), SU_ID << ID_OFFSET | 75, MIX_MASK},
  {ASCEND_REG(KICK_START_PC, lldb_kick_start_pc_ascend), SU_ID << ID_OFFSET | 76, MIX_MASK},
  {ASCEND_REG(SU_WARN_STATUS_0, lldb_su_warn_status_0_ascend), SU_ID << ID_OFFSET | 77, MIX_MASK},
  {ASCEND_REG(PB_SLOT_OFFSET, lldb_pb_slot_offset_ascend), SU_ID << ID_OFFSET | 128, AIV_MASK},
  {ASCEND_REG(PB_SLOT_ID, lldb_pb_slot_id_ascend), SU_ID << ID_OFFSET | 129, AIV_MASK},
  {ASCEND_REG(PB_SLOT_OCCUPY_BITMAP, lldb_pb_slot_occupy_bitmap_ascend), SU_ID << ID_OFFSET | 130, AIV_MASK},
  {ASCEND_REG(VEC_EVENT_TABLE, lldb_vec_event_table_ascend), SU_ID << ID_OFFSET | 131, AIV_MASK},
  {ASCEND_REG(CUBE_EVENT_TABLE, lldb_cube_event_table_ascend), SU_ID << ID_OFFSET | 132, AIC_MASK},
  {ASCEND_REG(FIXP_EVENT_TABLE, lldb_fixp_event_table_ascend), SU_ID << ID_OFFSET | 133, AIC_MASK},
  {ASCEND_REG(SCALAR_EVENT_TABLE, lldb_scalar_event_table_ascend), SU_ID << ID_OFFSET | 134, MIX_MASK},
  {ASCEND_REG(MTE1_EVENT_TABLE, lldb_mte1_event_table_ascend), SU_ID << ID_OFFSET | 135, AIC_MASK},
  {ASCEND_REG(MTE2_EVENT_TABLE, lldb_mte2_event_table_ascend), SU_ID << ID_OFFSET | 136, MIX_MASK},
  {ASCEND_REG(MTE3_EVENT_TABLE, lldb_mte3_event_table_ascend), SU_ID << ID_OFFSET | 137, AIV_MASK},
  {ASCEND_REG(GLB_GET_CNT, lldb_glb_get_cnt_ascend), SU_ID << ID_OFFSET | 5UL << 48, MIX_MASK},
  {ASCEND_REG(GLB_REL_CNT, lldb_glb_rel_cnt_ascend), SU_ID << ID_OFFSET | 5UL << 48 | 1UL << 47, MIX_MASK},
  {ASCEND_REG(SET_CROSS_CORE_CNT, lldb_set_cross_core_cnt_ascend), SU_ID << ID_OFFSET | 6UL << 48, MIX_MASK},
  {ASCEND_REG(SET_INTRA_BLK_CNT, lldb_set_intra_blk_cnt_ascend), SU_ID << ID_OFFSET | 6UL << 48 | 1UL << 47, MIX_MASK},
 
  {ASCEND_REG(MTE_WARN, lldb_mte_warn_ascend), MTE_ID << ID_OFFSET | 1UL << 48, MIX_MASK},
  {ASCEND_REG(L0_SET_VALUE_MTE, lldb_l0_set_value_mte_ascend), MTE_ID << ID_OFFSET | 2UL << 48, AIC_MASK},
  {ASCEND_REG(PADDING_MTE, lldb_padding_mte_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 1, AIC_MASK},
  {ASCEND_REG(PAD_VAL_OUTTOUB, lldb_pad_val_outtoub_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 2, AIV_MASK},
  {ASCEND_REG(PAD_VAL_OUTTOL1, lldb_pad_val_outtol1_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 3, AIC_MASK},
  {ASCEND_REG(LOOP_SIZE_OUTTOL1, lldb_loop_size_outtol1_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 4, AIC_MASK},
  {ASCEND_REG(LOOP1_STRIDE_OUTTOL1, lldb_loop1_stride_outtol1_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 5, AIC_MASK},
  {ASCEND_REG(LOOP2_STRIDE_OUTTOL1, lldb_loop2_stride_outtol1_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 6, AIC_MASK},
  {ASCEND_REG(LOOP_SIZE_OUTTOUB, lldb_loop_size_outtoub_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 7, AIV_MASK},
  {ASCEND_REG(LOOP1_STRIDE_OUTTOUB, lldb_loop1_stride_outtoub_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 8, AIV_MASK},
  {ASCEND_REG(LOOP2_STRIDE_OUTTOUB, lldb_loop2_stride_outtoub_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 9, AIV_MASK},
  {ASCEND_REG(LOOP_SIZE_UBTOOUT, lldb_loop_size_ubtoout_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 13, AIV_MASK},
  {ASCEND_REG(LOOP1_STRIDE_UBTOOUT, lldb_loop1_stride_ubtoout_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 14, AIV_MASK},
  {ASCEND_REG(LOOP2_STRIDE_UBTOOUT, lldb_loop2_stride_ubtoout_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 15, AIV_MASK},
  {ASCEND_REG(MTE2_NZ_PARA, lldb_mte2_nz_para_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 18, AIC_MASK},
  {ASCEND_REG(MTE2_SRC_PARA, lldb_mte2_src_para_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 20, AIC_MASK},
  {ASCEND_REG(PAD_CNT_NDDMA, lldb_pad_cnt_nddma_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 22, AIV_MASK},
  {ASCEND_REG(PAD_VAL_NDDMA, lldb_pad_val_nddma_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 23, AIV_MASK},
  {ASCEND_REG(LOOP0_STRIDE_NDDMA, lldb_loop0_stride_nddma_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 24, AIV_MASK},
  {ASCEND_REG(LOOP1_STRIDE_NDDMA, lldb_loop1_stride_nddma_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 25, AIV_MASK},
  {ASCEND_REG(LOOP2_STRIDE_NDDMA, lldb_loop2_stride_nddma_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 26, AIV_MASK},
  {ASCEND_REG(LOOP3_STRIDE_NDDMA, lldb_loop3_stride_nddma_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 27, AIV_MASK},
  {ASCEND_REG(LOOP4_STRIDE_NDDMA, lldb_loop4_stride_nddma_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 28, AIV_MASK},
  {ASCEND_REG(PCIE_RD_CTRL, lldb_pcie_rd_ctrl_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 29, AIV_MASK},
  {ASCEND_REG(PCIE_WR_CTRL, lldb_pcie_wr_ctrl_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 30, AIV_MASK},
  {ASCEND_REG(XGMMA_DTC, lldb_xgmma_dtc_ascend), MTE_ID << ID_OFFSET | 2UL << 48 | 32, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_0, lldb_xgamma_lut_inv_0_ascend), MTE_ID << ID_OFFSET | 5UL << 48, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_1, lldb_xgamma_lut_inv_1_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 1, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_2, lldb_xgamma_lut_inv_2_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 2, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_3, lldb_xgamma_lut_inv_3_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 3, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_4, lldb_xgamma_lut_inv_4_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 4, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_5, lldb_xgamma_lut_inv_5_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 5, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_6, lldb_xgamma_lut_inv_6_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 6, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_7, lldb_xgamma_lut_inv_7_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 7, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_8, lldb_xgamma_lut_inv_8_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 8, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_9, lldb_xgamma_lut_inv_9_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 9, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_10, lldb_xgamma_lut_inv_10_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 10, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_11, lldb_xgamma_lut_inv_11_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 11, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_12, lldb_xgamma_lut_inv_12_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 12, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_13, lldb_xgamma_lut_inv_13_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 13, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_14, lldb_xgamma_lut_inv_14_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 14, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_15, lldb_xgamma_lut_inv_15_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 15, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_16, lldb_xgamma_lut_inv_16_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 16, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_17, lldb_xgamma_lut_inv_17_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 17, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_18, lldb_xgamma_lut_inv_18_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 18, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_19, lldb_xgamma_lut_inv_19_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 19, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_20, lldb_xgamma_lut_inv_20_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 20, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_21, lldb_xgamma_lut_inv_21_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 21, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_22, lldb_xgamma_lut_inv_22_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 22, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_23, lldb_xgamma_lut_inv_23_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 23, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_24, lldb_xgamma_lut_inv_24_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 24, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_25, lldb_xgamma_lut_inv_25_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 25, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_26, lldb_xgamma_lut_inv_26_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 26, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_27, lldb_xgamma_lut_inv_27_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 27, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_28, lldb_xgamma_lut_inv_28_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 28, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_29, lldb_xgamma_lut_inv_29_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 29, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_30, lldb_xgamma_lut_inv_30_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 30, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_31, lldb_xgamma_lut_inv_31_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 31, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_32, lldb_xgamma_lut_inv_32_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 32, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_INV_33, lldb_xgamma_lut_inv_33_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 33, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_0, lldb_xgamma_lut_imp_0_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 34, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_1, lldb_xgamma_lut_imp_1_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 35, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_2, lldb_xgamma_lut_imp_2_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 36, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_3, lldb_xgamma_lut_imp_3_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 37, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_4, lldb_xgamma_lut_imp_4_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 38, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_5, lldb_xgamma_lut_imp_5_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 39, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_6, lldb_xgamma_lut_imp_6_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 40, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_7, lldb_xgamma_lut_imp_7_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 41, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_8, lldb_xgamma_lut_imp_8_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 42, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_9, lldb_xgamma_lut_imp_9_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 43, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_10, lldb_xgamma_lut_imp_10_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 44, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_11, lldb_xgamma_lut_imp_11_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 45, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_12, lldb_xgamma_lut_imp_12_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 46, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_13, lldb_xgamma_lut_imp_13_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 47, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_14, lldb_xgamma_lut_imp_14_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 48, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_15, lldb_xgamma_lut_imp_15_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 49, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_16, lldb_xgamma_lut_imp_16_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 50, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_17, lldb_xgamma_lut_imp_17_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 51, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_18, lldb_xgamma_lut_imp_18_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 52, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_19, lldb_xgamma_lut_imp_19_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 53, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_20, lldb_xgamma_lut_imp_20_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 54, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_21, lldb_xgamma_lut_imp_21_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 55, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_22, lldb_xgamma_lut_imp_22_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 56, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_23, lldb_xgamma_lut_imp_23_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 57, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_24, lldb_xgamma_lut_imp_24_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 58, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_25, lldb_xgamma_lut_imp_25_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 59, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_26, lldb_xgamma_lut_imp_26_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 60, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_27, lldb_xgamma_lut_imp_27_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 61, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_28, lldb_xgamma_lut_imp_28_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 62, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_29, lldb_xgamma_lut_imp_29_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 63, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_30, lldb_xgamma_lut_imp_30_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 64, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_31, lldb_xgamma_lut_imp_31_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 65, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_32, lldb_xgamma_lut_imp_32_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 66, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_33, lldb_xgamma_lut_imp_33_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 67, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_34, lldb_xgamma_lut_imp_34_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 68, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_35, lldb_xgamma_lut_imp_35_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 69, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_36, lldb_xgamma_lut_imp_36_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 70, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_37, lldb_xgamma_lut_imp_37_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 71, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_38, lldb_xgamma_lut_imp_38_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 72, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_39, lldb_xgamma_lut_imp_39_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 73, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_40, lldb_xgamma_lut_imp_40_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 74, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_41, lldb_xgamma_lut_imp_41_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 75, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_42, lldb_xgamma_lut_imp_42_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 76, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_43, lldb_xgamma_lut_imp_43_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 77, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_44, lldb_xgamma_lut_imp_44_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 78, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_45, lldb_xgamma_lut_imp_45_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 79, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_46, lldb_xgamma_lut_imp_46_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 80, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_47, lldb_xgamma_lut_imp_47_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 81, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_48, lldb_xgamma_lut_imp_48_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 82, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_49, lldb_xgamma_lut_imp_49_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 83, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_50, lldb_xgamma_lut_imp_50_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 84, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_51, lldb_xgamma_lut_imp_51_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 85, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_52, lldb_xgamma_lut_imp_52_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 86, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_53, lldb_xgamma_lut_imp_53_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 87, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_54, lldb_xgamma_lut_imp_54_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 88, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_55, lldb_xgamma_lut_imp_55_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 89, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_56, lldb_xgamma_lut_imp_56_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 90, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_57, lldb_xgamma_lut_imp_57_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 91, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_58, lldb_xgamma_lut_imp_58_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 92, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_59, lldb_xgamma_lut_imp_59_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 93, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_60, lldb_xgamma_lut_imp_60_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 94, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_61, lldb_xgamma_lut_imp_61_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 95, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_62, lldb_xgamma_lut_imp_62_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 96, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_63, lldb_xgamma_lut_imp_63_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 97, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_64, lldb_xgamma_lut_imp_64_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 98, MIX_MASK},
  {ASCEND_REG(XGAMMA_LUT_IMP_65, lldb_xgamma_lut_imp_65_ascend), MTE_ID << ID_OFFSET | 5UL << 48 | 99, MIX_MASK},
 
  {ASCEND_REG_32B(VREG0, lldb_vreg0_ascend), VEC_ID << ID_OFFSET | 2UL << 48, AIV_MASK},
  {ASCEND_REG_32B(VREG1, lldb_vreg1_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 16, AIV_MASK},
  {ASCEND_REG_32B(VREG2, lldb_vreg2_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 32, AIV_MASK},
  {ASCEND_REG_32B(VREG3, lldb_vreg3_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 48, AIV_MASK},
  {ASCEND_REG_32B(VREG4, lldb_vreg4_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 64, AIV_MASK},
  {ASCEND_REG_32B(VREG5, lldb_vreg5_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 80, AIV_MASK},
  {ASCEND_REG_32B(VREG6, lldb_vreg6_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 96, AIV_MASK},
  {ASCEND_REG_32B(VREG7, lldb_vreg7_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 112, AIV_MASK},
  {ASCEND_REG_32B(VREG8, lldb_vreg8_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 128, AIV_MASK},
  {ASCEND_REG_32B(VREG9, lldb_vreg9_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 144, AIV_MASK},
  {ASCEND_REG_32B(VREG10, lldb_vreg10_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 160, AIV_MASK},
  {ASCEND_REG_32B(VREG11, lldb_vreg11_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 176, AIV_MASK},
  {ASCEND_REG_32B(VREG12, lldb_vreg12_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 192, AIV_MASK},
  {ASCEND_REG_32B(VREG13, lldb_vreg13_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 208, AIV_MASK},
  {ASCEND_REG_32B(VREG14, lldb_vreg14_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 224, AIV_MASK},
  {ASCEND_REG_32B(VREG15, lldb_vreg15_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 240, AIV_MASK},
  {ASCEND_REG_32B(VREG16, lldb_vreg16_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 256, AIV_MASK},
  {ASCEND_REG_32B(VREG17, lldb_vreg17_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 272, AIV_MASK},
  {ASCEND_REG_32B(VREG18, lldb_vreg18_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 288, AIV_MASK},
  {ASCEND_REG_32B(VREG19, lldb_vreg19_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 304, AIV_MASK},
  {ASCEND_REG_32B(VREG20, lldb_vreg20_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 320, AIV_MASK},
  {ASCEND_REG_32B(VREG21, lldb_vreg21_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 336, AIV_MASK},
  {ASCEND_REG_32B(VREG22, lldb_vreg22_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 352, AIV_MASK},
  {ASCEND_REG_32B(VREG23, lldb_vreg23_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 368, AIV_MASK},
  {ASCEND_REG_32B(VREG24, lldb_vreg24_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 384, AIV_MASK},
  {ASCEND_REG_32B(VREG25, lldb_vreg25_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 400, AIV_MASK},
  {ASCEND_REG_32B(VREG26, lldb_vreg26_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 416, AIV_MASK},
  {ASCEND_REG_32B(VREG27, lldb_vreg27_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 432, AIV_MASK},
  {ASCEND_REG_32B(VREG28, lldb_vreg28_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 448, AIV_MASK},
  {ASCEND_REG_32B(VREG29, lldb_vreg29_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 464, AIV_MASK},
  {ASCEND_REG_32B(VREG30, lldb_vreg30_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 480, AIV_MASK},
  {ASCEND_REG_32B(VREG31, lldb_vreg31_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 496, AIV_MASK},
  {ASCEND_REG(PREG0, lldb_preg0_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 512, AIV_MASK},
  {ASCEND_REG(PREG1, lldb_preg1_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 514, AIV_MASK},
  {ASCEND_REG(PREG2, lldb_preg2_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 516, AIV_MASK},
  {ASCEND_REG(PREG3, lldb_preg3_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 518, AIV_MASK},
  {ASCEND_REG(PREG4, lldb_preg4_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 520, AIV_MASK},
  {ASCEND_REG(PREG5, lldb_preg5_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 522, AIV_MASK},
  {ASCEND_REG(PREG6, lldb_preg6_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 524, AIV_MASK},
  {ASCEND_REG(PREG7, lldb_preg7_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 526, AIV_MASK},
  {ASCEND_REG_32B(ULD_0, lldb_uld_0_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 1536, AIV_MASK},
  {ASCEND_REG_32B(ULD_1, lldb_uld_1_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 1537, AIV_MASK},
  {ASCEND_REG_32B(ULD_2, lldb_uld_2_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 1538, AIV_MASK},
  {ASCEND_REG_32B(ULD_3, lldb_uld_3_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 1539, AIV_MASK},
  {ASCEND_REG_32B(UST_DATA_0, lldb_ust_data_0_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2048, AIV_MASK},
  {ASCEND_REG_32B(UST_DATA_1, lldb_ust_data_1_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2049, AIV_MASK},
  {ASCEND_REG_32B(UST_DATA_2, lldb_ust_data_2_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2050, AIV_MASK},
  {ASCEND_REG_32B(UST_DATA_3, lldb_ust_data_3_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2051, AIV_MASK},
  {ASCEND_REG(UST_FLAG_0, lldb_ust_flag_0_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2052, AIV_MASK},
  {ASCEND_REG(UST_FLAG_1, lldb_ust_flag_1_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2053, AIV_MASK},
  {ASCEND_REG(UST_FLAG_2, lldb_ust_flag_2_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2054, AIV_MASK},
  {ASCEND_REG(UST_FLAG_3, lldb_ust_flag_3_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2055, AIV_MASK},
  {ASCEND_REG(SREG_0, lldb_sreg_0_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2560, AIV_MASK},
  {ASCEND_REG(SREG_1, lldb_sreg_1_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2561, AIV_MASK},
  {ASCEND_REG(SREG_2, lldb_sreg_2_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2562, AIV_MASK},
  {ASCEND_REG(SREG_3, lldb_sreg_3_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2563, AIV_MASK},
  {ASCEND_REG(SREG_4, lldb_sreg_4_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2564, AIV_MASK},
  {ASCEND_REG(SREG_5, lldb_sreg_5_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2565, AIV_MASK},
  {ASCEND_REG(SREG_6, lldb_sreg_6_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2566, AIV_MASK},
  {ASCEND_REG(SREG_7, lldb_sreg_7_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2567, AIV_MASK},
  {ASCEND_REG(SREG_8, lldb_sreg_8_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2568, AIV_MASK},
  {ASCEND_REG(SREG_9, lldb_sreg_9_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2569, AIV_MASK},
  {ASCEND_REG(SREG_10, lldb_sreg_10_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2570, AIV_MASK},
  {ASCEND_REG(SREG_11, lldb_sreg_11_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2571, AIV_MASK},
  {ASCEND_REG(SREG_12, lldb_sreg_12_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2572, AIV_MASK},
  {ASCEND_REG(SREG_13, lldb_sreg_13_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2573, AIV_MASK},
  {ASCEND_REG(SREG_14, lldb_sreg_14_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2574, AIV_MASK},
  {ASCEND_REG(SREG_15, lldb_sreg_15_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2575, AIV_MASK},
  {ASCEND_REG(SREG_16, lldb_sreg_16_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2576, AIV_MASK},
  {ASCEND_REG(SREG_17, lldb_sreg_17_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2577, AIV_MASK},
  {ASCEND_REG(SREG_18, lldb_sreg_18_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2578, AIV_MASK},
  {ASCEND_REG(SREG_19, lldb_sreg_19_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2579, AIV_MASK},
  {ASCEND_REG(SREG_20, lldb_sreg_20_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2580, AIV_MASK},
  {ASCEND_REG(SREG_21, lldb_sreg_21_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2581, AIV_MASK},
  {ASCEND_REG(SREG_22, lldb_sreg_22_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2582, AIV_MASK},
  {ASCEND_REG(SREG_23, lldb_sreg_23_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2583, AIV_MASK},
  {ASCEND_REG(SREG_24, lldb_sreg_24_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2584, AIV_MASK},
  {ASCEND_REG(SREG_25, lldb_sreg_25_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2585, AIV_MASK},
  {ASCEND_REG(SREG_26, lldb_sreg_26_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2586, AIV_MASK},
  {ASCEND_REG(SREG_27, lldb_sreg_27_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2587, AIV_MASK},
  {ASCEND_REG(SREG_28, lldb_sreg_28_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2588, AIV_MASK},
  {ASCEND_REG(SREG_29, lldb_sreg_29_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2589, AIV_MASK},
  {ASCEND_REG(SREG_30, lldb_sreg_30_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2590, AIV_MASK},
  {ASCEND_REG(SREG_31, lldb_sreg_31_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2591, AIV_MASK},
  {ASCEND_REG(SREG_32, lldb_sreg_32_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2592, AIV_MASK},
  {ASCEND_REG(SREG_33, lldb_sreg_33_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2593, AIV_MASK},
  {ASCEND_REG(SREG_34, lldb_sreg_34_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2594, AIV_MASK},
  {ASCEND_REG(SREG_35, lldb_sreg_35_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2595, AIV_MASK},
  {ASCEND_REG(SREG_36, lldb_sreg_36_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2596, AIV_MASK},
  {ASCEND_REG(SREG_37, lldb_sreg_37_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2597, AIV_MASK},
  {ASCEND_REG(SREG_38, lldb_sreg_38_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2598, AIV_MASK},
  {ASCEND_REG(SREG_39, lldb_sreg_39_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2599, AIV_MASK},
  {ASCEND_REG(SREG_40, lldb_sreg_40_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2600, AIV_MASK},
  {ASCEND_REG(SREG_41, lldb_sreg_41_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2601, AIV_MASK},
  {ASCEND_REG(SREG_42, lldb_sreg_42_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2602, AIV_MASK},
  {ASCEND_REG(SREG_43, lldb_sreg_43_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2603, AIV_MASK},
  {ASCEND_REG(SREG_44, lldb_sreg_44_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2604, AIV_MASK},
  {ASCEND_REG(SREG_45, lldb_sreg_45_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2605, AIV_MASK},
  {ASCEND_REG(SREG_46, lldb_sreg_46_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2606, AIV_MASK},
  {ASCEND_REG(SREG_47, lldb_sreg_47_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2607, AIV_MASK},
  {ASCEND_REG(SREG_48, lldb_sreg_48_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2608, AIV_MASK},
  {ASCEND_REG(SREG_49, lldb_sreg_49_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2609, AIV_MASK},
  {ASCEND_REG(SREG_50, lldb_sreg_50_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2610, AIV_MASK},
  {ASCEND_REG(SREG_51, lldb_sreg_51_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2611, AIV_MASK},
  {ASCEND_REG(SREG_52, lldb_sreg_52_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2612, AIV_MASK},
  {ASCEND_REG(SREG_53, lldb_sreg_53_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2613, AIV_MASK},
  {ASCEND_REG(SREG_54, lldb_sreg_54_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2614, AIV_MASK},
  {ASCEND_REG(SREG_55, lldb_sreg_55_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2615, AIV_MASK},
  {ASCEND_REG(SREG_56, lldb_sreg_56_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2616, AIV_MASK},
  {ASCEND_REG(SREG_57, lldb_sreg_57_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2617, AIV_MASK},
  {ASCEND_REG(SREG_58, lldb_sreg_58_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2618, AIV_MASK},
  {ASCEND_REG(SREG_59, lldb_sreg_59_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2619, AIV_MASK},
  {ASCEND_REG(SREG_60, lldb_sreg_60_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2620, AIV_MASK},
  {ASCEND_REG(SREG_61, lldb_sreg_61_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2621, AIV_MASK},
  {ASCEND_REG(SREG_62, lldb_sreg_62_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2622, AIV_MASK},
  {ASCEND_REG(SREG_63, lldb_sreg_63_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 2623, AIV_MASK},
  {ASCEND_REG_16B(VA_0, lldb_va_0_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3072, AIV_MASK},
  {ASCEND_REG_16B(VA_1, lldb_va_1_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3073, AIV_MASK},
  {ASCEND_REG_16B(VA_2, lldb_va_2_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3074, AIV_MASK},
  {ASCEND_REG_16B(VA_3, lldb_va_3_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3075, AIV_MASK},
  {ASCEND_REG_16B(VA_4, lldb_va_4_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3076, AIV_MASK},
  {ASCEND_REG_16B(VA_5, lldb_va_5_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3077, AIV_MASK},
  {ASCEND_REG_16B(VA_6, lldb_va_6_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3078, AIV_MASK},
  {ASCEND_REG_16B(VA_7, lldb_va_7_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3079, AIV_MASK},
  {ASCEND_REG(AREG_0, lldb_areg_0_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3584, AIV_MASK},
  {ASCEND_REG(AREG_1, lldb_areg_1_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3585, AIV_MASK},
  {ASCEND_REG(AREG_2, lldb_areg_2_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3586, AIV_MASK},
  {ASCEND_REG(AREG_3, lldb_areg_3_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3587, AIV_MASK},
  {ASCEND_REG(AREG_4, lldb_areg_4_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3588, AIV_MASK},
  {ASCEND_REG(AREG_5, lldb_areg_5_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3589, AIV_MASK},
  {ASCEND_REG(AREG_6, lldb_areg_6_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3590, AIV_MASK},
  {ASCEND_REG(AREG_7, lldb_areg_7_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 3591, AIV_MASK},
  {ASCEND_REG_16B(MASK, lldb_mask_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 4608, AIV_MASK},
  {ASCEND_REG(AR, lldb_ar_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 5632, AIV_MASK},
  {ASCEND_REG(VMS4_SR, lldb_vms4_sr_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 6144, AIV_MASK},
  {ASCEND_REG_32B(SQZN, lldb_sqzn_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 6656, AIV_MASK},
  {ASCEND_REG(VPC, lldb_vpc_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 7168, AIV_MASK},
  {ASCEND_REG(VL, lldb_vl_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 7680, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_0, lldb_agu_am_const_0_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8192, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_1, lldb_agu_am_const_1_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8193, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_2, lldb_agu_am_const_2_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8194, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_3, lldb_agu_am_const_3_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8195, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_4, lldb_agu_am_const_4_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8196, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_5, lldb_agu_am_const_5_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8197, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_6, lldb_agu_am_const_6_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8198, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_7, lldb_agu_am_const_7_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8199, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_8, lldb_agu_am_const_8_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8200, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_9, lldb_agu_am_const_9_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8201, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_10, lldb_agu_am_const_10_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8202, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_11, lldb_agu_am_const_11_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8203, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_12, lldb_agu_am_const_12_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8204, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_13, lldb_agu_am_const_13_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8205, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_14, lldb_agu_am_const_14_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8206, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_15, lldb_agu_am_const_15_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8207, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_16, lldb_agu_am_const_16_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8208, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_17, lldb_agu_am_const_17_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8209, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_18, lldb_agu_am_const_18_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8210, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_19, lldb_agu_am_const_19_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8211, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_20, lldb_agu_am_const_20_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8212, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_21, lldb_agu_am_const_21_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8213, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_22, lldb_agu_am_const_22_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8214, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_23, lldb_agu_am_const_23_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8215, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_24, lldb_agu_am_const_24_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8216, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_25, lldb_agu_am_const_25_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8217, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_26, lldb_agu_am_const_26_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8218, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_27, lldb_agu_am_const_27_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8219, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_28, lldb_agu_am_const_28_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8220, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_29, lldb_agu_am_const_29_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8221, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_30, lldb_agu_am_const_30_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8222, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_31, lldb_agu_am_const_31_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8223, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_32, lldb_agu_am_const_32_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8224, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_33, lldb_agu_am_const_33_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8225, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_34, lldb_agu_am_const_34_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8226, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_35, lldb_agu_am_const_35_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8227, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_36, lldb_agu_am_const_36_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8228, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_37, lldb_agu_am_const_37_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8229, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_38, lldb_agu_am_const_38_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8230, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_39, lldb_agu_am_const_39_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8231, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_40, lldb_agu_am_const_40_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8232, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_41, lldb_agu_am_const_41_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8233, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_42, lldb_agu_am_const_42_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8234, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_43, lldb_agu_am_const_43_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8235, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_44, lldb_agu_am_const_44_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8236, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_45, lldb_agu_am_const_45_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8237, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_46, lldb_agu_am_const_46_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8238, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_47, lldb_agu_am_const_47_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8239, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_48, lldb_agu_am_const_48_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8240, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_49, lldb_agu_am_const_49_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8241, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_50, lldb_agu_am_const_50_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8242, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_51, lldb_agu_am_const_51_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8243, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_52, lldb_agu_am_const_52_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8244, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_53, lldb_agu_am_const_53_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8245, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_54, lldb_agu_am_const_54_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8246, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_55, lldb_agu_am_const_55_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8247, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_56, lldb_agu_am_const_56_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8248, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_57, lldb_agu_am_const_57_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8249, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_58, lldb_agu_am_const_58_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8250, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_59, lldb_agu_am_const_59_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8251, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_60, lldb_agu_am_const_60_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8252, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_61, lldb_agu_am_const_61_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8253, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_62, lldb_agu_am_const_62_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8254, AIV_MASK},
  {ASCEND_REG(AGU_AM_CONST_63, lldb_agu_am_const_63_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8255, AIV_MASK},
  {ASCEND_REG(UST_ELE_OFS_0, lldb_ust_ele_ofs_0_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8704, AIV_MASK},
  {ASCEND_REG(UST_ELE_OFS_1, lldb_ust_ele_ofs_1_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8705, AIV_MASK},
  {ASCEND_REG(UST_ELE_OFS_2, lldb_ust_ele_ofs_2_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8706, AIV_MASK},
  {ASCEND_REG(UST_ELE_OFS_3, lldb_ust_ele_ofs_3_ascend), VEC_ID << ID_OFFSET | 2UL << 48 | 8707, AIV_MASK},
  {ASCEND_REG(CORE_ID, lldb_core_id_ascend), VEC_ID << ID_OFFSET | 9UL << 48, AIV_MASK},
  {ASCEND_REG(VEC_CORE_ID, lldb_vec_core_id_ascend), VEC_ID << ID_OFFSET | 9UL << 48 | 1, AIV_MASK},
  {ASCEND_REG(VTHREADDIM_x, lldb_vthreaddim_x_ascend), VEC_ID << ID_OFFSET | 9UL << 48 | 2, AIV_MASK},
  {ASCEND_REG(VTHREADDIM_y, lldb_vthreaddim_y_ascend), VEC_ID << ID_OFFSET | 9UL << 48 | 3, AIV_MASK},
  {ASCEND_REG(VTHREADDIM_z, lldb_vthreaddim_z_ascend), VEC_ID << ID_OFFSET | 9UL << 48 | 4, AIV_MASK},
  {ASCEND_REG(SIMT_PC, lldb_simt_pc_ascend), VEC_ID << ID_OFFSET | 9UL << 48 | 16384, AIV_MASK},
  {ASCEND_REG_32B(MRF, lldb_mrf_ascend), VEC_ID << ID_OFFSET | 9UL << 48 | 81920, AIV_MASK},
  {ASCEND_REG(P_REGISTER, lldb_p_register_ascend), VEC_ID << ID_OFFSET | 9UL << 48 | 98304, AIV_MASK},
  {ASCEND_REG(EXECMASK, lldb_execmask_ascend), VEC_ID << ID_OFFSET | 9UL << 48 | 114688, AIV_MASK},
 
  {ASCEND_REG(FMATRIX, lldb_fmatrix_ascend), L1_ID << ID_OFFSET | 0, AIC_MASK},
  {ASCEND_REG(PADDING_L1, lldb_padding_l1_ascend), L1_ID << ID_OFFSET | 1, AIC_MASK},
  {ASCEND_REG(L0_SET_VALUE_L1, lldb_l0_set_value_l1_ascend), L1_ID << ID_OFFSET | 2, AIC_MASK},
  {ASCEND_REG(L1_3D_SIZE, lldb_l1_3d_size_ascend), L1_ID << ID_OFFSET | 3, AIC_MASK},
  {ASCEND_REG(L3D_RPT, lldb_l3d_rpt_ascend), L1_ID << ID_OFFSET | 4, AIC_MASK},
  {ASCEND_REG(FMATRIX_DUAL_0, lldb_fmatrix_dual_0_ascend), L1_ID << ID_OFFSET | 5, AIC_MASK},
  {ASCEND_REG(FMATRIX_DUAL_1, lldb_fmatrix_dual_1_ascend), L1_ID << ID_OFFSET | 6, AIC_MASK},
  {ASCEND_REG(FMATRIX_B, lldb_fmatrix_b_ascend), L1_ID << ID_OFFSET | 7, AIC_MASK},
  {ASCEND_REG(L3D_RPT_B, lldb_l3d_rpt_b_ascend), L1_ID << ID_OFFSET | 8, AIC_MASK},
  {ASCEND_REG(PADDING_B, lldb_padding_b_ascend), L1_ID << ID_OFFSET | 9, AIC_MASK},
  {ASCEND_REG(RELU_ALPHA, lldb_relu_alpha_ascend), L1_ID << ID_OFFSET | 1UL << 48, AIC_MASK},
  {ASCEND_REG(QUANT_POST, lldb_quant_post_ascend), L1_ID << ID_OFFSET | 1UL << 48 | 1, AIC_MASK},
  {ASCEND_REG(FPC, lldb_fpc_ascend), L1_ID << ID_OFFSET | 1UL << 48 | 2, AIC_MASK},
  {ASCEND_REG(QUANT_PRE, lldb_quant_pre_ascend), L1_ID << ID_OFFSET | 1UL << 48 | 3, AIC_MASK},
  {ASCEND_REG(ELT_SRC_PARA, lldb_elt_src_para_ascend), L1_ID << ID_OFFSET | 1UL << 48 | 4, AIC_MASK},
  {ASCEND_REG(LOOP3_PARA, lldb_loop3_para_ascend), L1_ID << ID_OFFSET | 1UL << 48 | 5, AIC_MASK},
  {ASCEND_REG(FIX_CLIP_RELU, lldb_fix_clip_relu_ascend), L1_ID << ID_OFFSET | 1UL << 48 | 6, AIC_MASK},
  {ASCEND_REG(LOOP4_PARA, lldb_loop4_para_ascend), L1_ID << ID_OFFSET | 1UL << 48 | 7, AIC_MASK},
  {ASCEND_REG(CHANNEL_PARA, lldb_channel_para_ascend), L1_ID << ID_OFFSET | 1UL << 48 | 8, AIC_MASK},
  {ASCEND_REG(ELT_ANTIQ_PARA, lldb_elt_antiq_para_ascend), L1_ID << ID_OFFSET | 1UL << 48 | 9, AIC_MASK},
  {ASCEND_REG(L1_WARN, lldb_l1_warn_ascend), L1_ID << ID_OFFSET | 7UL << 48, AIC_MASK}
};
 
static_assert(sizeof(REGISTER_950_INFO) / sizeof(DeviceRegisterInfo) == k_num_registers_ascend,
              "REGISTER_950_INFO size is invalid");
 
const RegExtractor &RegisterInfoPOSIX_ascend950::GetRegExtractor() {
  static RegExtractor instance(REGISTER_950_INFO, k_num_su_registers);
  LLDB_LOGF(GetLog(LLDBLog::Process), "raw_register_infos_size=%lu",
            instance.raw_register_infos.size());
  return instance;
}
 
RegisterInfoPOSIX_ascend950::RegisterInfoPOSIX_ascend950(const ArchSpec &target_arch)
  : RegisterInfoPOSIX_ascend(target_arch, k_num_su_registers,
    k_last_gpr_ascend - k_first_gpr_ascend + 1,
    GetRegExtractor().raw_register_infos.data(),
    GetRegExtractor().register_map) {
}
 
const RegisterSet* RegisterInfoPOSIX_ascend950::GetRegisterSet(size_t set_index) const {
  if (set_index < GetRegisterSetCount())
    return &g_reg_sets_ascend950[set_index];
  return nullptr;
}
 
Status RegisterInfoPOSIX_ascend950::GetRegisterAddr(const llvm::StringRef reg_name,
  CoreType core_type, uint64_t &addr) {
  Status error;
  auto reg_info = m_register_map.find(reg_name.str());
  if (reg_info == m_register_map.end()) {
    error.SetErrorStringWithFormatv(
        "Can not get addr, register name: {0}", reg_name);
  }
  if ((1U << static_cast<int>(core_type)) & reg_info->second.core_type_support_mask) {
    addr = reg_info->second.addr;
  } else {
    error.SetErrorStringWithFormatv(
        "Can not get addr, register {0} is not support", reg_name);
  }
  return error;
}

uint64_t RegisterInfoPOSIX_ascend950::GetDbgAddr(uint64_t addr) {
    addr |= (SU_ID << ID_OFFSET);
    return addr;
}

// ============== RegisterInfoPOSIXCore_ascend950 =================
const RegExtractor &RegisterInfoPOSIXCore_ascend950::GetRegExtractor() {
  static RegExtractor instance(REGISTER_950_INFO, k_num_registers_ascend);
  LLDB_LOGF(GetLog(LLDBLog::Process), "raw_register_infos_size=%lu",
            instance.raw_register_infos.size());
  return instance;
}
 
RegisterInfoPOSIXCore_ascend950::RegisterInfoPOSIXCore_ascend950(const ArchSpec &target_arch)
  : RegisterInfoPOSIX_ascend950(target_arch, k_num_registers_ascend,
    k_num_gpr_registers,
    GetRegExtractor().raw_register_infos.data(),
    GetRegExtractor().register_map) {
}
 
RegisterInfoPOSIX_ascend950::RegisterInfoPOSIX_ascend950(const ArchSpec &target_arch, uint32_t register_info_count,
  uint32_t register_gpr_count, const RegisterInfo *register_info_p,
  const std::map<std::string, DeviceRegisterInfo>& register_map)
  : RegisterInfoPOSIX_ascend(target_arch, register_info_count,
    register_gpr_count, register_info_p, register_map) {
}
 
static const RegisterSet g_core_reg_sets[k_num_register_sets] = {
  {"SURegisters", "su_dbg_reg", k_num_su_registers, g_su_regnums_ascend950},
  {"MTERegisters", "mte_dbg_reg", k_num_mte_registers, g_mte_regnums_ascend950},
  {"VECRegisters", "vec_dbg_reg", k_num_vecrb_registers, g_vecrb_regnums_ascend950},
  {"L1Registers", "l1_dbg_reg", k_num_l1_registers, g_l1_regnums_ascend950},
};
 
const RegisterSet* RegisterInfoPOSIXCore_ascend950::GetRegisterSet(size_t set_index) const {
  if (set_index < GetRegisterSetCount())
    return &g_core_reg_sets[set_index];
  LLDB_LOGF(GetLog(LLDBLog::Thread), "get A2/A3 core register set failed");
  return nullptr;
}
 
size_t RegisterInfoPOSIXCore_ascend950::GetRegisterSetCount() const {
  return k_num_register_sets;
}

#endif