/*
* Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 */
#ifdef MS_DEBUGGER
#include "RegisterInfoPOSIX_ascend310P.h"
#include "lldb/Utility/LLDBLog.h"
using namespace lldb_private;
using namespace lldb;

namespace {
enum LLDB_ASCEND_RENUM {
  k_first_gpr_ascend,
  lldb_x0_ascend = k_first_gpr_ascend,
  lldb_x1_ascend,
  lldb_x2_ascend,
  lldb_x3_ascend,
  lldb_x4_ascend,
  lldb_x5_ascend,
  lldb_x6_ascend,
  lldb_x7_ascend,
  lldb_x8_ascend,
  lldb_x9_ascend,
  lldb_x10_ascend,
  lldb_x11_ascend,
  lldb_x12_ascend,
  lldb_x13_ascend,
  lldb_x14_ascend,
  lldb_x15_ascend,
  lldb_x16_ascend,
  lldb_x17_ascend,
  lldb_x18_ascend,
  lldb_x19_ascend,
  lldb_x20_ascend,
  lldb_x21_ascend,
  lldb_x22_ascend,
  lldb_x23_ascend,
  lldb_x24_ascend,
  lldb_x25_ascend,
  lldb_x26_ascend,
  lldb_x27_ascend,
  lldb_x28_ascend,
  lldb_x29_ascend,
  lldb_x30_ascend,
  lldb_x31_ascend,
  k_last_gpr_ascend = lldb_x31_ascend,
  lldb_pc_ascend,
  lldb_blockid_ascend,
  lldb_status_ascend,
  lldb_ctrl_ascend,
  lldb_para_base_ascend,
  lldb_data_main_base_ascend,
  lldb_data_ub_base_ascend,
  lldb_data_size_ascend,
  lldb_lpcnt_ascend,
  lldb_blockdim_ascend,
  lldb_fmatrix_ascend,
  lldb_condition_flag_ascend,
  lldb_deqscale_ascend,
  lldb_padding_ascend,
  lldb_l2_vaddr_base_ascend,
  lldb_l0_set_value_ascend,
  lldb_coreid_ascend,
  lldb_vms4_sr_ascend,
  lldb_l2_in_main_ascend,
  lldb_prn_cor_ir_ascend,
  lldb_arch_ver_ascend,
  lldb_smmu_tag_ver_ascend,
  lldb_l1_3d_size_ascend,
  lldb_aipp_spr_0_ascend,
  lldb_aipp_spr_1_ascend,
  lldb_aipp_spr_2_ascend,
  lldb_aipp_spr_3_ascend,
  lldb_aipp_spr_4_ascend,
  lldb_aipp_spr_5_ascend,
  lldb_aipp_spr_6_ascend,
  lldb_aipp_spr_7_ascend,
  lldb_aipp_spr_8_ascend,
  lldb_aipp_spr_9_ascend,
  lldb_aipp_spr_10_ascend,
  lldb_aipp_spr_11_ascend,
  lldb_aipp_spr_12_ascend,
  lldb_aipp_spr_13_ascend,
  lldb_aipp_spr_14_ascend,
  lldb_aipp_spr_15_ascend,
  lldb_aipp_spr_16_ascend,
  lldb_aipp_spr_17_ascend,
  lldb_aipp_spr_18_ascend,
  lldb_aipp_spr_19_ascend,
  lldb_aipp_spr_20_ascend,
  lldb_aipp_spr_21_ascend,
  lldb_aipp_spr_22_ascend,
  lldb_aipp_spr_23_ascend,
  lldb_aipp_spr_24_ascend,
  lldb_data_exp_0_ascend,
  lldb_data_exp_1_ascend,
  lldb_data_exp_2_ascend,
  lldb_data_exp_3_ascend,
  lldb_low_pre_tbl_ascend,
  lldb_smask_index_ascend,
  lldb_k_num_ascend,
  lldb_rpn_offset_ascend,
  lldb_varf0_ascend,
  lldb_varf1_ascend,
  lldb_varf2_ascend,
  lldb_varf3_ascend,
  lldb_varf4_ascend,
  lldb_varf5_ascend,
  lldb_varf6_ascend,
  lldb_varf7_ascend,
  lldb_mask_ascend,
  lldb_cmpmask_ascend,
  k_num_registers_ascend
};
} // namespace

static const uint32_t g_regnums_ascend310p[] = {
  lldb_x0_ascend,  lldb_x1_ascend,  lldb_x2_ascend, lldb_x3_ascend,
  lldb_x4_ascend,  lldb_x5_ascend, lldb_x6_ascend,  lldb_x7_ascend,
  lldb_x8_ascend, lldb_x9_ascend,  lldb_x10_ascend, lldb_x11_ascend,
  lldb_x12_ascend, lldb_x13_ascend, lldb_x14_ascend, lldb_x15_ascend,
  lldb_x16_ascend, lldb_x17_ascend, lldb_x18_ascend, lldb_x19_ascend,
  lldb_x20_ascend, lldb_x21_ascend, lldb_x22_ascend, lldb_x23_ascend,
  lldb_x24_ascend, lldb_x25_ascend, lldb_x26_ascend, lldb_x27_ascend,
  lldb_x28_ascend, lldb_x29_ascend, lldb_x30_ascend, lldb_x31_ascend,
  lldb_pc_ascend, lldb_blockid_ascend, lldb_status_ascend, lldb_ctrl_ascend,
  lldb_para_base_ascend, lldb_data_main_base_ascend, lldb_data_ub_base_ascend,
  lldb_data_size_ascend, lldb_lpcnt_ascend, lldb_blockdim_ascend,
  lldb_fmatrix_ascend, lldb_condition_flag_ascend, lldb_deqscale_ascend,
  lldb_padding_ascend, lldb_l2_vaddr_base_ascend, lldb_l0_set_value_ascend,
  lldb_coreid_ascend, lldb_vms4_sr_ascend, lldb_l2_in_main_ascend,
  lldb_prn_cor_ir_ascend, lldb_arch_ver_ascend, lldb_smmu_tag_ver_ascend,
  lldb_l1_3d_size_ascend, lldb_aipp_spr_0_ascend, lldb_aipp_spr_1_ascend,
  lldb_aipp_spr_2_ascend, lldb_aipp_spr_3_ascend, lldb_aipp_spr_4_ascend,
  lldb_aipp_spr_5_ascend, lldb_aipp_spr_6_ascend, lldb_aipp_spr_7_ascend,
  lldb_aipp_spr_8_ascend, lldb_aipp_spr_9_ascend, lldb_aipp_spr_10_ascend,
  lldb_aipp_spr_11_ascend, lldb_aipp_spr_12_ascend, lldb_aipp_spr_13_ascend,
  lldb_aipp_spr_14_ascend, lldb_aipp_spr_15_ascend, lldb_aipp_spr_16_ascend,
  lldb_aipp_spr_17_ascend, lldb_aipp_spr_18_ascend, lldb_aipp_spr_19_ascend,
  lldb_aipp_spr_20_ascend, lldb_aipp_spr_21_ascend, lldb_aipp_spr_22_ascend,
  lldb_aipp_spr_23_ascend, lldb_aipp_spr_24_ascend, lldb_data_exp_0_ascend,
  lldb_data_exp_1_ascend, lldb_data_exp_2_ascend, lldb_data_exp_3_ascend,
  lldb_low_pre_tbl_ascend, lldb_smask_index_ascend, lldb_k_num_ascend,
  lldb_rpn_offset_ascend, lldb_varf0_ascend, lldb_varf1_ascend,
  lldb_varf2_ascend, lldb_varf3_ascend, lldb_varf4_ascend, lldb_varf5_ascend,
  lldb_varf6_ascend, lldb_varf7_ascend, lldb_mask_ascend, lldb_cmpmask_ascend,
  LLDB_INVALID_REGNUM};

static const RegisterSet g_reg_sets_ascend310p[] = {
  {"Registers", "register", lldb_cmpmask_ascend - lldb_x0_ascend + 1,
   g_regnums_ascend310p}};

static const DeviceRegisterInfo REGISTER_310P_INFO[] = {
    {ASCEND_GPR(PC, pc, LLDB_REGNUM_GENERIC_PC), 0},
    {ASCEND_REG(BLOCKID, lldb_blockid_ascend), 1},
    {ASCEND_REG(STATUS, lldb_status_ascend), 2},
    {ASCEND_REG(CTRL, lldb_ctrl_ascend), 3},
    {ASCEND_REG(PARA_BASE, lldb_para_base_ascend), 4},
    {ASCEND_REG(DATA_MAIN_BASE, lldb_data_main_base_ascend), 5},
    {ASCEND_REG(DATA_UB_BASE, lldb_data_ub_base_ascend), 6},
    {ASCEND_REG(DATA_SIZE, lldb_data_size_ascend), 7},
    {ASCEND_REG(LPCNT, lldb_lpcnt_ascend), 8},
    {ASCEND_REG(BLOCKDIM, lldb_blockdim_ascend), 9},
    {ASCEND_REG(FMATRIX, lldb_fmatrix_ascend), 10},
    {ASCEND_REG(CONDITION_FLAG, lldb_condition_flag_ascend), 11},
    {ASCEND_REG(DEQSCALE, lldb_deqscale_ascend), 12},
    {ASCEND_REG(PADDING, lldb_padding_ascend), 13},
    {ASCEND_REG(L2_VADDR_BASE, lldb_l2_vaddr_base_ascend), 14},
    {ASCEND_REG(L0_SET_VALUE, lldb_l0_set_value_ascend), 15},
    {ASCEND_REG(COREID, lldb_coreid_ascend), 16},
    {ASCEND_REG(VMS4_SR, lldb_vms4_sr_ascend), 17},
    {ASCEND_REG(L2_IN_MAIN, lldb_l2_in_main_ascend), 18},
    {ASCEND_REG(PRN_COR_IR, lldb_prn_cor_ir_ascend), 19},
    {ASCEND_REG(ARCH_VER, lldb_arch_ver_ascend), 20},
    {ASCEND_REG(SMMU_TAG_VER, lldb_smmu_tag_ver_ascend), 21},
    {ASCEND_REG(L1_3D_SIZE, lldb_l1_3d_size_ascend), 22},
    {ASCEND_REG(AIPP_SPR_0, lldb_aipp_spr_0_ascend), 23},
    {ASCEND_REG(AIPP_SPR_1, lldb_aipp_spr_1_ascend), 24},
    {ASCEND_REG(AIPP_SPR_2, lldb_aipp_spr_2_ascend), 25},
    {ASCEND_REG(AIPP_SPR_3, lldb_aipp_spr_3_ascend), 26},
    {ASCEND_REG(AIPP_SPR_4, lldb_aipp_spr_4_ascend), 27},
    {ASCEND_REG(AIPP_SPR_5, lldb_aipp_spr_5_ascend), 28},
    {ASCEND_REG(AIPP_SPR_6, lldb_aipp_spr_6_ascend), 29},
    {ASCEND_REG(AIPP_SPR_7, lldb_aipp_spr_7_ascend), 30},
    {ASCEND_REG(AIPP_SPR_8, lldb_aipp_spr_8_ascend), 31},
    {ASCEND_REG(AIPP_SPR_9, lldb_aipp_spr_9_ascend), 32},
    {ASCEND_REG(AIPP_SPR_10, lldb_aipp_spr_10_ascend), 33},
    {ASCEND_REG(AIPP_SPR_11, lldb_aipp_spr_11_ascend), 34},
    {ASCEND_REG(AIPP_SPR_12, lldb_aipp_spr_12_ascend), 35},
    {ASCEND_REG(AIPP_SPR_13, lldb_aipp_spr_13_ascend), 36},
    {ASCEND_REG(AIPP_SPR_14, lldb_aipp_spr_14_ascend), 37},
    {ASCEND_REG(AIPP_SPR_15, lldb_aipp_spr_15_ascend), 38},
    {ASCEND_REG(AIPP_SPR_16, lldb_aipp_spr_16_ascend), 39},
    {ASCEND_REG(AIPP_SPR_17, lldb_aipp_spr_17_ascend), 40},
    {ASCEND_REG(AIPP_SPR_18, lldb_aipp_spr_18_ascend), 41},
    {ASCEND_REG(AIPP_SPR_19, lldb_aipp_spr_19_ascend), 42},
    {ASCEND_REG(AIPP_SPR_20, lldb_aipp_spr_20_ascend), 43},
    {ASCEND_REG(AIPP_SPR_21, lldb_aipp_spr_21_ascend), 44},
    {ASCEND_REG(AIPP_SPR_22, lldb_aipp_spr_22_ascend), 45},
    {ASCEND_REG(AIPP_SPR_23, lldb_aipp_spr_23_ascend), 46},
    {ASCEND_REG(AIPP_SPR_24, lldb_aipp_spr_24_ascend), 47},
    {ASCEND_REG(DATA_EXP_0, lldb_data_exp_0_ascend), 48},
    {ASCEND_REG(DATA_EXP_1, lldb_data_exp_1_ascend), 49},
    {ASCEND_REG(DATA_EXP_2, lldb_data_exp_2_ascend), 50},
    {ASCEND_REG(DATA_EXP_3, lldb_data_exp_3_ascend), 51},
    {ASCEND_REG(LOW_PRE_TBL, lldb_low_pre_tbl_ascend), 52},
    {ASCEND_REG(SMASK_INDEX, lldb_smask_index_ascend), 53},
    {ASCEND_REG(K_NUM, lldb_k_num_ascend), 54},
    {ASCEND_REG(RNN_OFFSET, lldb_rpn_offset_ascend), 55},
    {ASCEND_GPR(GPR0, x0, LLDB_INVALID_REGNUM), 64},
    {ASCEND_GPR(GPR1, x1, LLDB_INVALID_REGNUM), 65},
    {ASCEND_GPR(GPR2, x2, LLDB_INVALID_REGNUM), 66},
    {ASCEND_GPR(GPR3, x3, LLDB_INVALID_REGNUM), 67},
    {ASCEND_GPR(GPR4, x4, LLDB_INVALID_REGNUM), 68},
    {ASCEND_GPR(GPR5, x5, LLDB_INVALID_REGNUM), 69},
    {ASCEND_GPR(GPR6, x6, LLDB_INVALID_REGNUM), 70},
    {ASCEND_GPR(GPR7, x7, LLDB_INVALID_REGNUM), 71},
    {ASCEND_GPR(GPR8, x8, LLDB_INVALID_REGNUM), 72},
    {ASCEND_GPR(GPR9, x9, LLDB_INVALID_REGNUM), 73},
    {ASCEND_GPR(GPR10, x10, LLDB_INVALID_REGNUM), 74},
    {ASCEND_GPR(GPR11, x11, LLDB_INVALID_REGNUM), 75},
    {ASCEND_GPR(GPR12, x12, LLDB_INVALID_REGNUM), 76},
    {ASCEND_GPR(GPR13, x13, LLDB_INVALID_REGNUM), 77},
    {ASCEND_GPR(GPR14, x14, LLDB_INVALID_REGNUM), 78},
    {ASCEND_GPR(GPR15, x15, LLDB_INVALID_REGNUM), 79},
    {ASCEND_GPR(GPR16, x16, LLDB_INVALID_REGNUM), 80},
    {ASCEND_GPR(GPR17, x17, LLDB_INVALID_REGNUM), 81},
    {ASCEND_GPR(GPR18, x18, LLDB_INVALID_REGNUM), 82},
    {ASCEND_GPR(GPR19, x19, LLDB_INVALID_REGNUM), 83},
    {ASCEND_GPR(GPR20, x20, LLDB_INVALID_REGNUM), 84},
    {ASCEND_GPR(GPR21, x21, LLDB_INVALID_REGNUM), 85},
    {ASCEND_GPR(GPR22, x22, LLDB_INVALID_REGNUM), 86},
    {ASCEND_GPR(GPR23, x23, LLDB_INVALID_REGNUM), 87},
    {ASCEND_GPR(GPR24, x24, LLDB_INVALID_REGNUM), 88},
    {ASCEND_GPR(GPR25, x25, LLDB_INVALID_REGNUM), 89},
    {ASCEND_GPR(GPR26, x26, LLDB_INVALID_REGNUM), 90},
    {ASCEND_GPR(GPR27, x27, LLDB_INVALID_REGNUM), 91},
    {ASCEND_GPR(GPR28, x28, LLDB_INVALID_REGNUM), 92},
    {ASCEND_GPR_ALT(GPR29, x29, fp, LLDB_REGNUM_GENERIC_FP), 93},
    {ASCEND_GPR_ALT(GPR30, x30, sp, LLDB_REGNUM_GENERIC_SP), 94},
    {ASCEND_GPR_ALT(GPR31, x31, lr, LLDB_REGNUM_GENERIC_RA), 95},
    {ASCEND_REG(VARF0, lldb_varf0_ascend), 96},
    {ASCEND_REG(VARF1, lldb_varf1_ascend), 97},
    {ASCEND_REG(VARF2, lldb_varf2_ascend), 98},
    {ASCEND_REG(VARF3, lldb_varf3_ascend), 99},
    {ASCEND_REG(VARF4, lldb_varf4_ascend), 100},
    {ASCEND_REG(VARF5, lldb_varf5_ascend), 101},
    {ASCEND_REG(VARF6, lldb_varf6_ascend), 102},
    {ASCEND_REG(VARF7, lldb_varf7_ascend), 103},
    {ASCEND_REG(MASK, lldb_mask_ascend), 104},
    {ASCEND_REG(CMPMASK, lldb_cmpmask_ascend), 105},
};

static_assert(sizeof(REGISTER_310P_INFO) / sizeof(DeviceRegisterInfo) == k_num_registers_ascend,
              "REGISTER_310P_INFO size is invalid");

const RegExtractor &RegisterInfoPOSIX_ascend310P::GetRegExtractor() {
  static RegExtractor instance(REGISTER_310P_INFO, k_num_registers_ascend);
  LLDB_LOGF(GetLog(LLDBLog::Process), "raw_register_infos_size=%lu",
            instance.raw_register_infos.size());
  return instance;
}

RegisterInfoPOSIX_ascend310P::RegisterInfoPOSIX_ascend310P(const ArchSpec &target_arch)
  : RegisterInfoPOSIX_ascend(target_arch, k_num_registers_ascend,
    k_last_gpr_ascend - k_first_gpr_ascend + 1,
    GetRegExtractor().raw_register_infos.data(),
    GetRegExtractor().register_map) {
}

const RegisterSet* RegisterInfoPOSIX_ascend310P::GetRegisterSet(size_t set_index) const {
  if (set_index < GetRegisterSetCount())
    return &g_reg_sets_ascend310p[set_index];
  LLDB_LOGF(GetLog(LLDBLog::Thread), "get 310P register set failed");
  return nullptr;
}

Status RegisterInfoPOSIX_ascend310P::GetRegisterAddr(const llvm::StringRef reg_name,
  CoreType core_type, uint64_t &addr) {
  Status error;
  auto reg_info = m_register_map.find(reg_name.str());
  if (reg_info == m_register_map.end()) {
    error.SetErrorStringWithFormatv(
        "Can not get addr, register name: {0}", reg_name);
    return error;
  }
  addr = reg_info->second.addr;
  return error;
}

#endif
